### PR TITLE
Release v1.6.0

### PR DESCRIPTION
**Pull request by jimdickinson**

### CODE REVIEW

**Review by bradfordcp — COMMENTED** [review]
Scanned through the changes. This looks good!

**Comment by bradfordcp** [comment]
Are we worried about the smoke tests failing?

**Review by respringer — APPROVED** [review]

**Comment by jimdickinson** [comment]
> Are we worried about the smoke tests failing?

I'm surprised, but I saw problems with GKE yesterday, so we may need to tweak some of our automation. All of the integration tests passed on Jenkins on the commit this one is based on, so this PR is just bumping some artifacts used to install the release.

**Comment by jimdickinson** [comment]
Should've heeded @bradfordcp 's warning. Do over in #388

**Pull request merged**
